### PR TITLE
Mobile fix

### LINKED ISSUE #135: Mobile Touch Event List Transparency
image

When scrolling on mobile, after hitting one of the list items with my thumb, it makes that single list item "active" and fades out the rest, even after lifting up thumb.

This behavior is intended for mouse activity. The UX works well on desktop only, but not on touchscreens. 

Disable this behavior for mobile, and test for scrolling in both up and down directions.

### PR DESCRIPTION
**Pull request by obeys**
Resolves #135

### CODE REVIEW

**Comment by obeys** [comment]
erm I think I may have broken something

**Comment by obeys** [comment]
fixed the site breaking css changes!

**Review by 0x4007 — CHANGES_REQUESTED** [review]
This is done wrong. The behavior needs to be the same with mouse and disabled on mobile touch only

**Comment by obeys** [comment]
> This is done wrong. The behavior needs to be the same with mouse and disabled on mobile touch only

Could you elaborate more about that? I believe the current implementation handles the mouse hover correctly and disables the fading effect on mobile devices. video below to showcase

https://github.com/user-attachments/assets/c6061831-eaa8-4439-81ad-4f4870626039

**Comment by 0x4007** [comment]
I was expecting event handlers and such let me test on computer later but your video looks promising thanks!

**Review by 0x4007 — APPROVED** [review]
My mistake

**Pull request merged**
