### PR TITLE
feat: add labels to preview when necessary

### LINKED ISSUE #142: Add labels at issue preview body
When we click on an issue we should show the labels - price, time, priority - inside the body specially at mobile view, but I guess it's benefic in Desktop too. This way a user can navigate using the buttons and still get a feel for the issue's characteristics.

Forcefully adding the div as an example:

image

### PR DESCRIPTION
**Pull request by zugdev**
Resolves #142

https://github.com/user-attachments/assets/a6589d66-8e3a-401a-8247-06ec8aef07da

### CODE REVIEW

**Comment by 0x4007** [comment]
Mixed feelings on how it looks on mobile but the bottom can't be scrolled to all the way at least in iOS now with the labels offsetting the inner height.

**Comment by 0x4007** [comment]
I think the labels would look better on the bottom on mobile for sure.

**Comment by zugdev** [comment]
> but the bottom can't be scrolled to all the way at least in iOS now with the labels offsetting the inner height. 

Do you mean you cant scroll to the bottom of the issue list? I've added another PR to add some padding

**Comment by zugdev** [comment]
> I think the labels would look better on the bottom on mobile for sure. 

Will try it!

**Comment by 0x4007** [comment]
> > but the bottom can't be scrolled to all the way at least in iOS now with the labels offsetting the inner height. 
> 
> Do you mean you cant scroll to the bottom of the issue list? I've added another PR to add some padding
> 

It should be in this pull because this pull introduced the problem.

**Comment by 0x4007** [comment]
https://github.com/user-attachments/assets/e9876e47-544f-4f01-b133-e4663661031f

**Comment by 0x4007** [comment]
I just realized that the problem is in production. I think another recent pull introduced the problem.  

The footer bar is too tall now. I must have overlooked it in another pull.

**Comment by zugdev** [comment]
> I just realized that the problem is in production. I think another recent pull introduced the problem.
> 
> The footer bar is too tall now. I must have overlooked it in another pull.

Yeah me too, it was introduced in #137 when toolbar was refactored. #145 is a quick solution.

**Comment by zugdev** [comment]
> I think the labels would look better on the bottom on mobile for sure.

Do you have stacked or side by side in mind? I'll attach some quick illustrations for comparison:

Stacked:

image

image

Side by side:

image

image

Side by side can be good if I can reduce buttons a little, but labels will wrap when too big. 

IPhone XR demo:

image

**Comment by 0x4007** [comment]
Side by side but if I had to choose stacked I would make the control buttons on top.

**Comment by zugdev** [comment]
@0x4007 lmk what you think about this.

**Review by 0x4007 — APPROVED** [review]
Super clean on mobile. Not sure on desktop but I'm assuming you also did well there. 

A bit concerned about those void statements. I'm not sure if an error is thrown if it will be caught.

**Pull request merged**
