### PR TITLE
Fixing broken cache in text filter

### LINKED ISSUE #66: Text Filter Seems Broken
I put a very specific search query, so I expect it to only filter down to a single task. However it seems to be broken. 

It could be related to an invalid issue preview in my cache, as you can see that the error was thrown. 

work ubq fi_ (1)

### PR DESCRIPTION
**Pull request by Sadaf-A**
Resolves #66

### CODE REVIEW

**Review by 0x4007 — CHANGES_REQUESTED** [review]
Fix your formatting

**Review by 0x4007 — COMMENTED** [review]
Actually this might be correct if you just moved the whole thing in the block. Although that doesn't seem optimal. Can you move only the relevant part inside the try catch please?

Telling CI to do a deploy so I can test now.

**Comment by 0x4007** [comment]
As it turns out I can't login and test from my phone. Hope somebody else can take over!

**Comment by Sadaf-A** [comment]
@0x4007 how does it look now?

**Review by 0x4007 — APPROVED** [review]

**Comment by 0x4007** [comment]
I didn't test that it works but the code looks good.

**Comment by Sadaf-A** [comment]
@Keyrxng could you please provide your inputs here?

**Comment by Keyrxng** [comment]
> I put a very specific search query, so I expect it to only filter down to a single task. However it seems to be broken.

> It could be related to an invalid issue preview in my cache, as you can see that the error was thrown.

@Sadaf-A as far as I understand the spec the following needs to be resolved:

- When you search for an issue the preview box should be filled with the issue details not `"No task found for preview id 2292677641"` which is happening on the preview deployment as well as locally for me

> so I expect it to only filter down to a single task.

It's unclear to me whether the spec aims to have the listed issues on the left become a single item if you enter a very specific term but the preview box should display similar details as when you manually click on the issue

P.S With PRs that change/fix UI problems remember to include a screenshot of that issue after it has been resolved

**Comment by Sadaf-A** [comment]
> > I put a very specific search query, so I expect it to only filter down to a single task. However it seems to be broken.
> 
> > It could be related to an invalid issue preview in my cache, as you can see that the error was thrown.
> 
> @Sadaf-A as far as I understand the spec the following needs to be resolved:
> 
> * When you search for an issue the preview box should be filled with the issue details not `"No task found for preview id 2292677641"` which is happening on the preview deployment as well as locally for me
> 
> > so I expect it to only filter down to a single task.
> 
> It's unclear to me whether the spec aims to have the listed issues on the left become a single item if you enter a very specific term but the preview box should display similar details as when you manually click on the issue
> 
> P.S With PRs that change/fix UI problems remember to include a screenshot of that issue after it has been resolved

I wrapped the whole function responsible for rendering from cache with a try and catch block so if it threw an error it will render from network. If the error is still being thrown then it could be possible that the error is thrown when we fetch from the network

**Comment by Keyrxng** [comment]
@Sadaf-A I had another look at things.

- The list of issues should reduce down to one item, when the error modal is visible it does not remove items from the list.

- The error box appears when you arrive to the page with a fresh cache and you try to search. If you refresh the page and try again the error will not appear.

- I manually looked through the cached issue IDs (may have been after refresh, you should also check before too) and could not see the ID which is in the error box maybe you'll want to manually confirm this too

- I'd focus on where the error is thrown from and work back from there debugging until you can resolve or elegantly handle it.

> but the preview box should display similar details as when you manually click on the issue

Forgive me here, I mistook the error notification for the issue preview modal because I was using a different screen size. When you search `toy "demo"` you should see only one issue which you can select via keyboard nav or clicking and it'll render the preview modal.

I hope this is of more help to you, sorry if not.

**Pull request closed without merging**
