### PR TITLE
feat: offline working progressive webapp 

### LINKED ISSUE #90: Progressive Web App
At this conference, there were several instances where I had bad signal, and I generally like to pitch by showing this interface. 

The problem is that it loads the issues after you load the page so it takes a moment and I'm staring at an empty screen essentially.

Turning this into a progressive Web app should allow us to instantly load the cached issues, even when off-line or disconnected

### PR DESCRIPTION
**Pull request by zugdev**
Resolves #90

Currently working offline by caching issues. When we load we get issues from cache and start trying to fetch from json. If it's successful we check if there are new issues, if so we cache them and re-display issues.

No network demo:

[noNetwork.webm](https://github.com/user-attachments/assets/8099ce8e-dca7-4df9-8ec2-d13f9a3e4578)

Cached issues are in sync:

[alreadyCached.webm](https://github.com/user-attachments/assets/a024da43-5732-4225-850f-d9069d3c5893)

Cached issues not in sync:

[fetchAndCache.webm](https://github.com/user-attachments/assets/38493c07-15cb-4098-b6db-8cb88ceeaa23)

### CODE REVIEW

**Comment by zugdev** [comment]
This already makes the entire app work offline. We need to add a better icon the current one looks very wrong in my device.

**Comment by zugdev** [comment]
Refac on PWA based in [this document.](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Offline_Service_workers)

**Comment by 0x4007** [comment]
9ababa2

image

**Comment by zugdev** [comment]
> 9ababa2
> 
> image

yeah that's why I switched to a draft. there are some google requirements I have to investigate a little

**Comment by zugdev** [comment]
Working offline but look how weird it behaves hahah

[weird.webm](https://github.com/user-attachments/assets/e92814f4-0133-4936-b555-0252988e9e25)

**Comment by zugdev** [comment]
@0x4007 test it out and please let me remove `console.log()`s before you merge.

**Comment by 0x4007** [comment]
image

Check the authentication that should probably be tweaked for this?

**Comment by zugdev** [comment]
Let's just skip auth if completely offline. We could cache user but I believe it's just not worth it.

**Comment by zugdev** [comment]
This PR should handle both scenarios well, I am caching issues and loading from cache on page render - at the same time, we fire a request to update issues in cache. If you have bad reception it'll load instantaneously from cache and eventually reload if cached != fetched. If you are completely offline you only have access to cache.

**Review by 0x4007 — APPROVED** [review]
QA works code looks fine

**Comment by 0x4007** [comment]
> @0x4007 test it out and please let me remove `console.log()`s before you merge.

Let me know when you want to merge.

**Comment by zugdev** [comment]
> > @0x4007 test it out and please let me remove `console.log()`s before you merge.
> 
> Let me know when you want to merge. 

Already removed comments, pls go ahead

**Pull request merged**
