### PR TITLE
feat: markdown footnote rendering

### LINKED ISSUE #167: proper display for citations
As can be seen in [this issue](https://work.ubq.fi/?issue=2607517148), citations aren't properly handled and look ugly. There is no viable CSS only solution, but perhaps markdown can fix it.

See the bottom of the picture:

image

### PR DESCRIPTION
**Pull request by koya0**
Resolves #167 

# QA
### Prod display:
image

### Current display:
image

### Prod display:
image

### Current display:
image

### Prod display:
image

### Current display:
image

### CODE REVIEW

**Comment by zugdev** [comment]
I'd make footnotes an h3, looks too big.

**Comment by zugdev** [comment]
I think this is good, the copilot extensions looks a little weird but it's not your fault, probably a failed bot remaining operation. 

image

please check if u can make footnotes h3 instead and we can proceed

**Review by zugdev — APPROVED** [review]

**Comment by koya0** [comment]
> I think this is good, the copilot extensions looks a little weird but it's not your fault, probably a failed bot remaining operation. 
> 
> image
> 
> please check if u can make footnotes h3 instead and we can proceed
> 
> 
> 
> 

I guess footnotes are h2 by default from Github, the `marked` function just "translate" markdown to HTML, so I think its more complex to make this change

**Comment by zugdev** [comment]
alright makes sense, the h2 comes from the body itself not from ur change

**Pull request merged**
